[project]
name = "ck-roofline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=6.29.5",
    "jupyterlab>=4.4.3",
    "plotly[express]>=6.1.2",
    "polars>=1.30.0",
    "pyarrow>=20.0.0",
]
